### ISSUE TITLE
Can't deal with file router

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch-network.github.io#144]
![image](https://user-images.githubusercontent.com/54882546/233318497-f84e1d2b-b765-4cb4-b9f1-5ca02e4683f5.png)

Router will automatically remove the file name suffix.
![image](https://user-images.githubusercontent.com/54882546/233318967-668ab296-44d1-4291-bafa-0dd731c5307a.png)

Should jump according to url
![image](https://user-images.githubusercontent.com/54882546/233319098-6aa1e2ec-8fea-41aa-b4af-4a8c2f8692f3.png)

**Comment by Mine77** [comment]
can you elaborate more? how do you set the URL for the link?

**Comment by geometryolife** [comment]
> can you elaborate more? how do you set the URL for the link?

When redirecting to addresses with file names such as .md, the routing of the website will automatically remove the .md suffix, resulting in redirecting to incorrect addresses.

**Comment by Mine77** [comment]
This might be a problem with the local environment. The deployed version is fine.
