### ISSUE TITLE
Increase the jump speed of some links

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch-network.github.io#149]
Tonight's meeting discusses some small problems, such as some link jumps will be delayed, maybe because the routing jump is transferred, resulting in a delay.

**Comment by wow-sven** [comment]
Currently the docs route has latency, I think this is what's causing it.

I found out that this is where it started
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/6805130/233418930-4ce04b3b-ebb3-4e5f-96b2-2ff92c203958.png">

The code here is handling clicking on docs is going to Introduction not rooch

@geometryolife You can see if there are other options，the current scheme is my own thinking, not found in the official documents

**Comment by Mine77** [comment]
Just change the nested folder structure to separate docs should be fine. So there's no need for redirecting.
#152

**Comment by Mine77** [comment]
any other links with issues?

**Comment by Mine77** [comment]
reverted my PR.
Just noticed that we still need redirect because the siltelinks need to be redirected as well. #151

**Comment by Mine77** [comment]
fixed with #157.

**Comment by Mine77** [comment]
Fixed that by changing the URL directly: #180
