### ISSUE TITLE
[bug]Search function is broken.

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch-network.github.io#188]
<img width="965" alt="Screen Shot 2023-06-01 at 12 23 30" src="https://github.com/rooch-network/rooch-network.github.io/assets/77268/4c7c7865-3166-47c1-9152-04192b9c55e5">

https://discord.com/channels/1078938449974935592/1087634725243453501/1113665965989826673

**Comment by geometryolife** [comment]
Fix by #189
