### ISSUE TITLE
[docs] link breaking

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch-network.github.io#194]
Link: https://rooch.network/docs/rooch

Fraud Proof and Move Language links should direct to https://rooch.network/docs/tech-highlights/fraud-proof and https://rooch.network/docs/tech-highlights/move-language

**Comment by geometryolife** [comment]
@feliciss Do you mean the links can not access?

**Comment by feliciss** [comment]
> @feliciss Do you mean the links can not access?

I meant that

> Fraud Proof and Move Language links should direct to https://rooch.network/docs/tech-highlights/fraud-proof and https://rooch.network/docs/tech-highlights/move-language

The original links are https://rooch.network/docs/fraud-proof and https://rooch.network/docs/move-language

Don't worry, I can fix them.

**Comment by feliciss** [comment]
Resolved by #195
