### ISSUE TITLE
QA: answers to frequently asked questions

### ISSUE THREAD

**Issue by templexxx** [rooch-network/rooch-network.github.io#31]
economy & technology questions only:

1. What are the usage scenarios for token?
2. Why does rooch token be used as gas easier than other layer2? What's the important technology behind it?
3. What would be the benefits after I moving my DApp from etherum written by solidty to rooch?  What's the cost?
4. What will happen when I trying to use multi chains settlement for moving assert from one to another chain? 
5. From a DApp perspective, what is the cost of cross-chain asset transformation with the help of rooch? How big is it? Why not to use bridge instead?

**Comment by Mine77** [comment]
will incorporate these into the v0.2 milestone.
