### ISSUE TITLE
Introduce zk solution with zkMove

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch-network.github.io#36]
1. Update https://rooch.network/docs/technology/modular-blockchain-architecture/, add zk solution on Arbitration layer.
2. Update https://rooch.network/docs/technology/fraud-proofs, and describe how to integrate optimistic and zk(or add a new page). the optimistic run first, and use zk to reduce the challenge period.

**Comment by Mine77** [comment]
will incorporate these into the v0.2 milestone.

**Comment by Mine77** [comment]
done with article retwrite
