### ISSUE TITLE
Why the multi-chain settlement layer2 is more secure than cross-chain

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch-network.github.io#40]
1. The multi-chain value to DApp
1. How multi-chain settlement worked.
2. Why is multi-chain settlement a better solution than the cross-chain bridge?

**Comment by templexxx** [comment]
How multi-chain settlement worked.
----

It would be impressive to explain the various conditions it will encounter and point out our design, knowing that we have done serious work.
