### ISSUE TITLE
Website Content Additions

### ISSUE THREAD

**Issue by ren-ryder** [rooch-network/rooch-network.github.io#43]
We need to add a basic partners section on the main page where we can add different partner logos. This should go on the main page at the bottom, above the footer. At some point we can move this to its own separate page but for now I believe the strongest impact would be to include it on the front page. 

Example: https://mystenlabs.com/partners

Also, we need to add a branding page where other institutions can access our branding materials.
Example:  https://blog.celestia.org/

Possibly, this may necessitate a new logo design segment in the near future, but a simple solution for now is fine. 

Add a socials logo thumbnail link for @RoochNetwork twitter at the top right of the page next to the github and light/dark theme toggle.

**Comment by Mine77** [comment]
will incorporate all these into the v0.2 milestone development and re-organize.
