### ISSUE TITLE
Add twitter and medium link to website

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch-network.github.io#62]

**Comment by geometryolife** [comment]
![image](https://user-images.githubusercontent.com/54882546/221155243-ff7d1939-b6ad-46c3-a2be-fa0370118f43.png)
Do we add a new tab such as "Links" or use a single page?

**Comment by jolestar** [comment]
<img width="1203" alt="Screen Shot 2023-02-28 at 05 33 03" src="https://user-images.githubusercontent.com/77268/221690573-d8e59af2-f2c9-4451-bfec-54cabbc8fbfc.png">

Just at bottom
