### ISSUE TITLE
Category filter for the Blog page

### ISSUE THREAD

**Issue by Mine77** [rooch-network/rooch-network.github.io#73]
Adding a sidebar or a head bar as a filter for separating different types of blog posts.

**Comment by Mine77** [comment]
More details on this feature:
In each blog post, there are the following metadata:
* Title - The name of the blog post that will show up on the blog indexing page
* Description - A short description of the blog post that will show up on the blog indexing page
* Author - The author of the blog post
* Date - The publishing date of the post
* Category - The category of the post. (e.g. Technology, Web3, Product, Partnership....)
* Slug (If needed)

For the filter component here, I was hoping it can be a <ul> component with <li> multiple buttons.
When selecting each button, the page only displays the specific categories of articles.
The styling is not required for now.

**Comment by wow-sven** [comment]
https://github.com/rooch-network/rooch-network.github.io/pull/88

**Comment by Mine77** [comment]
New idea, can we separate different categories of blogs with different folders?
also still use the filter to display different categories of articles.
e.g.
```
-- blog/technology/
----- post1.mdx
----- post2.mdx
-- blog/partnership/
----- post3.mdx
----- post4.mdx
```

**Comment by geometryolife** [comment]
> New idea, can we separate different categories of blogs with different folders? also still use the filter to display different categories of articles. e.g.
> 
> ```
> -- blog/technology/
> ----- post1.mdx
> ----- post2.mdx
> -- blog/partnership/
> ----- post3.mdx
> ----- post4.mdx
> ```

It will be affected website routes currently if we use the way that split folder.

**Comment by wow-sven** [comment]
https://github.com/rooch-network/rooch-network.github.io/pull/103

**Comment by Mine77** [comment]
filter is done in #114
