### ISSUE TITLE
Preparing for styling

### ISSUE THREAD

**Issue by Mine77** [rooch-network/rooch-network.github.io#75]
* Research about CSS frameworks:  [Tailwind CSS](https://tailwindcss.com/) vs [Bulma](https://bulma.io/) and make a choice
* Find a UI Kit
* Add the CSS framework as well as the UI kit to the project

**Comment by Mine77** [comment]
Tailwind still has the most features and is more powerful.
Bulma is simple to use the final code will be cleaner but its functionality is limited.
We will go with Tailwind CSS.

**Comment by wow-sven** [comment]
I need to use styles when developing blog filters, so I added this first

https://github.com/rooch-network/rooch-network.github.io/pull/88

**Comment by geometryolife** [comment]
Close by #89
