### ISSUE TITLE
Keep the original links to the blogs

### ISSUE THREAD

**Issue by Mine77** [rooch-network/rooch-network.github.io#83]
We want to keep the original links for the blog posts.

**Comment by Mine77** [comment]
It might be better if we include a blog post template in the blog folder and make it hidden.

**Comment by geometryolife** [comment]
> Figure out a way to keep the URL of each blog post to be the same one as the v0.1 version site.

The blog URL is already the same as before, but the docs need to do some work for the beautiful slug.
