### ISSUE TITLE
Include a blog post template in the blog folder and make it hidden

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch-network.github.io#85]
It might be better if we include a blog post template in the blog folder and make it hidden.

_Originally posted by @Mine77 in https://github.com/rooch-network/rooch-network.github.io/issues/83#issuecomment-1489813365_
            
The docs need to do some work for the beautiful slug.
We need to use a router config for the docs to make it keep the original URL and keep the file prefix.

**Comment by Mine77** [comment]
this issue is about creating a blog template. I created it under `/pages` folder to avoid showing it up
